# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd68496911455673a9951f37a7d4049ddd6afb7730ad923ce434fbb8f5dd3f4fd884570c7b86e422e6919fcf20587fc969457f73c16d94c4ff47b930aa1b6cf8

test:
  secret_key_base: b1b71c9a8d9bc361b9dedbe361e0848683e9388081944ddd2aa528c51cf44354dbd0d2a10686a89030774da1719fc2366f2a5c76d07d01595fd03aeeb5ddee52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
